apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "Nv6PGPo7B0IQMjdompOzSbk0jktl6VS5CAVWRJSVeNp4Mb0nE9jxkt93MAYiafrg\nA3/eoK8XYYX5dNR9JK0FGy0J0usHQ1Py7UilK1i26vCViDnLiP3Obw73aVepHbbs\nqiLGj2kuSqOxzgep2R96ZWc/zkldMazXjsDhqlsvjcc="
