apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "1VUaGq4Qad35Q7m5sN2vXR+64dHzfvLyYObq+1dGLhtF9eIp99SyNJls6e2VFahF\npOdBOoR6PJw63O0M+elwO99w225vtrnxHLjr055wS6QL4fpNxX13Qpq533Njx4p9\nT+dWRd87VYBPVLpJTdUu7WoKhtKTsLyAeJU/v6GVQe0="
