apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "y1ruwxXUg3OTMFJmzxbDwBsNjPcUbX/VW+48YDzymDqJqRFHK746RYGcIl7yPkh9\nSh4c9GDeMiGpKwFKDf9vFygtUDcAf4e20mX+hPknN/asN8pubweTZtxN/0iUgZH1\nZYNpVfGkS02cFrf7I8jl6baPmq65nuA9g7qmwtzi4lU="
